services:

  backend:
    container_name: todolist
    image: nathansiegfrid/todolist-go
    build: .
    ports:
    - ${API_PORT:-8080}:8080
    depends_on:
    - postgres
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: app
      PG_PASSWORD: app
      PG_DATABASE: app

  postgres:
    container_name: postgres
    image: postgres:16
    shm_size: 128mb
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
