services:
  backend:
    container_name: todolist
    image: nathansiegfrid/todolist
    build: .
    ports:
      - ${API_PORT:-8080}:8080
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
      JWT_SECRET: ${JWT_SECRET}

  postgres:
    container_name: postgres
    image: postgres:17
    shm_size: 128mb
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
