services:
  postgres:
    container_name: postgres
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app

  backend:
    container_name: todolist
    image: nathansiegfrid/todolist-go
    build: .
    depends_on:
    - postgres
    ports:
    - ${API_PORT:-8080}:8080
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: app
      PG_PASSWORD: app
      PG_DATABASE: app
    # Temporary fix before retry connect DB is implemented.
    restart: on-failure:10
